version: '3'

services:
  nginx:
    build: .
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
